extend = "../../pyproject.toml"

[lint.pep8-naming]
extend-ignore-names = [
    "{Tod,Trm,Top,Tmax,dT}",
    "{Tod,Trm,Top,Tmax,dT}_*",
    "*_{Tod,Trm,Top,Tmax,dT}",
    "*_{Tod,Trm,Top,Tmax,dT}_*",
]
